EmployeeRegister/Controllers/AuthenticationController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using EmployeeRegister.BusinessLogic.Interfaces;
using EmployeeRegister.Common.Enums;
using EmployeeRegister.Common.Models;
using EmployeeRegister.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeRegister.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IUserService _userService;
        private readonly IAuthService _authService;

        public AuthenticationController(IUserService userService, IAuthService authService)
        {
            _userService = userService;
            _authService = authService;
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("HomePage", "Home");
            }
            
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLoginViewModel userLoginViewModel)
        {
            if (ModelState.IsValid)
            {               
                if (_authService.IsLogin(userLoginViewModel.Login, userLoginViewModel.Password, out int id))
                {
                    User user = _userService.Get(id);
                    
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Email),
                        new Claim(ClaimTypes.Role, ((Role)user.Role).ToString())
                    };

                    var claimIdentity =
                        new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimIdentity));
                        
                    return RedirectToAction("HomePage","Home");
                }
            }

            return View(userLoginViewModel);
        }
        
        public IActionResult Registration()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registration(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                if (_authService.IsRegistration(userViewModel.Login, userViewModel.Email))
                {
                    return View(userViewModel);
                }
                
                _userService.Create(new User
                {
                    Email = userViewModel.Email,
                    Login = userViewModel.Login,
                    Password = userViewModel.Password,
                    Role = 0
                });
                
                return RedirectToAction(nameof(Login));
            }

            return View(userViewModel);
        }
        
        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("HomePage", "Home");
        }
    }
}

EmployeeRegister/Views/Authentication/Login.cshtml
@model EmployeeRegister.ViewModels.UserLoginViewModel
@{
    ViewData["Title"] = "Login";
}
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/css/BootsWatchLux.css" />
    <title>Login</title>
</head>

<body>
<form asp-controller="Authentication" asp-action="Login" method="post">
        <div class="uiforvalidation">
        @Html.ValidationSummary()
    </div>
        <p></p>
        <div class="form-group text-center">
        <label >Login: </label>
            @Html.TextBoxFor(x => x.Login)
        </div>
        <p></p>
        <div class="form-group text-center">
        <label>Password: </label>
            @Html.TextBoxFor(x => x.Password, new { size = 16, @type="password" })
            </div>
        <p></p>
    <div class="text-center">
            <input class="btn btn-dark" type="submit" value="Login">
    </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>

EmployeeRegister/Views/Authentication/Registration.cshtml
@model EmployeeRegister.ViewModels.UserViewModel

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/css/BootsWatchLux.css" />
    <title>Registration</title>
</head>

<body>
<form asp-controller="Authentication" asp-action="Registration" method="post">
        <div class="uiforvalidation">
            @Html.ValidationSummary()
        </div>
    <p></p>
        <div class="form-group text-center">
        <label class="control-label">Login: </label>
        @Html.TextBoxFor(x => x.Login, new {size=32})
    </div>
        <p></p>
        <div class="form-group text-center">
        <label class="control-label">Email: </label>
            @Html.TextBoxFor(x => x.Email, new {size=32})
    </div>
        <p></p>
        <div class="form-group text-center">
        <label class="control-label">Password: </label>
        @Html.TextBoxFor(x => x.Password, new {size=28, @type="Password"})
    </div>
        <p></p>
        <div class="form-group text-center">
        <label class="control-label">Confirm password: </label>
            @Html.TextBoxFor(x => x.ConfirmPassword, new {size=21, @type="Password"})
    </div>
        <p></p>
        <div class="text-center">
            <input class="btn btn-dark" type="submit" value="Registration">
        </div>

</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>